server:
  port: ${PORT:8012}

spring:
  application:
    name: pm-api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
      routes:
        - id: company
          uri: lb://pm-company-ws
          predicates:
            - Path=/company
          filters:
            - AuthorizationHeaderFilter

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://afrozeprojectmanagement.us.auth0.com/

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

management:
  endpoint:
    health:
      show-details: always
      enabled: true
  endpoints:
    web:
      exposure:
        include: beans,health,httptrace,info,metrics,circuitbreakers,circuitbreakerevents

logging:
  level:
    org:
      springframework:
        web: DEBUG
        security: DEBUG

info:
  application:
    name: ${spring.application.name}