server:
  port: ${PORT:0}

spring:
  application:
    name: pm-project-ws
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://afrozeprojectmanagement.us.auth0.com/.well-known/jwks.json
          issuer-uri: https://afrozeprojectmanagement.us.auth0.com/

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

management:
  endpoint:
    health:
      show-details: always
      enabled: true
  endpoints:
    web:
      exposure:
        include: beans,health,httptrace,info,metrics,circuitbreakers,circuitbreakerevents

logging:
  level:
    org:
      springframework:
        web:
          client: WARN
        security: TRACE

info:
  application:
    name: ${spring.application.name}